### ISSUE TITLE
Naglasiti koja slika treba da bude podrazumevani thumbnail za stranu

### ISSUE THREAD

**Issue by aleksandar-stefanovic** [riskmatf/riskmatf.github.io#9]
Trenutno, kada se neka stranica podeli negde (e.g. Facebook i ostale društvene mreže), crawler-i ne znaju koju sliku da izaberu za thumbnail, i to dovodi do situacija poput:
![screenshot from 2018-12-10 11 19 36](https://user-images.githubusercontent.com/6058082/49726076-73d87300-fc6d-11e8-881f-c5d0b3015ccb.png)
Gde je thumbnail za datu stranu generičan i neinformativan o tome šta se zapravo nalazi na stranici.

Rešenje je dato ovde: https://stackoverflow.com/questions/2090179/how-to-specify-an-image-to-appear-in-facebook-link-to-your-site

Nisam siguran kako bismo ovo implementirali kao opciono, e.g. ako neko naglasi da želi određenu sliku, onda da se to stavi kao meta-informacija, a u protivnom, ako se ne naglasi, da ništa ne bude izmenjeno...

**Comment by ffilipovicc98** [comment]
Dodati u header stranice
```html
<meta property="og:title" content="Naslov stranice" />
<meta property="og:type" content="website" />
<meta property="og:url" content="url koji se nikad nece menjati" />
<meta property="og:image" content="link ili putanja do slike" />
```

Napomena: Verovatno nakon dodavanja ovih tagova nece doci do promene prilikom narednih slanja linka. Ako je ikada putem facebook-a podeljen link fejs(i drugi sajtovi koji podrzavaju opengraph) mu dodeli podrazumevani izgled i zapamti ga kao takvog. Da bi se isforsirale promene, neophodno je koristiti sledecu alatku:

[https://developers.facebook.com/tools/debug/sharing/](url)

Takodje zgodno da se testira koja slika se najvise uklapa.

Vise o open graph-u na [http://ogp.me/](url)

**Comment by aleksandar-stefanovic** [comment]
Iz nekog razloga GitHub ne povezuje pull request sa ovom stranicom, pa zato, pull request je ovaj: #13
